In [2]:
import numpy as np

In [5]:
list1 = [10,20,30]
list1

[10, 20, 30]

In [6]:
arr1 = np.array(list1)
arr1

array([10, 20, 30])

In [7]:
arr2 = np.arange(10,20,1) #start, stop, step
arr2

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [9]:
arr3dim = np.array([[[1,2,3],[3,4,5]],[[5,6,7],[7,8,9]]])
arr3dim

array([[[1, 2, 3],
        [3, 4, 5]],

       [[5, 6, 7],
        [7, 8, 9]]])

In [10]:
arr3dim.shape

(2, 2, 3)

In [11]:
arr3dim * 3

array([[[ 3,  6,  9],
        [ 9, 12, 15]],

       [[15, 18, 21],
        [21, 24, 27]]])

In [12]:
arr2 * 5

array([50, 55, 60, 65, 70, 75, 80, 85, 90, 95])

In [17]:
arr4 = arr1 * arr1
arr4

array([100, 400, 900])

In [22]:
arr4[0]

100

In [19]:
arr3dim[1]

array([[5, 6, 7],
       [7, 8, 9]])

In [20]:
arr4.sum()

1400

In [21]:
arr4.var()

108888.88888888888

In [23]:
for x in arr1:
    print(x)

10
20
30


In [24]:
for x in np.nditer(arr3dim):
    print(x)

1
2
3
3
4
5
5
6
7
7
8
9


In [25]:
np.save("new", arr1)

In [26]:
np.load("new.npy")

array([10, 20, 30])

In [27]:
np.savetxt("new.txt", arr1,delimiter=',')

In [28]:
np.loadtxt("new.txt",delimiter=',')

array([10., 20., 30.])